package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"go-graphql/internal/transport/graphql/graph"
	"go-graphql/internal/transport/graphql/model"
)

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	posts, err := r.PostUsecase.GetPosts(ctx)
	if err != nil {
		return nil, err
	}

	var result []*model.Post
	for _, p := range posts {
		result = append(result, &model.Post{
			ID:          p.ID,
			Title:       p.Title,
			Description: p.Description,
		})
	}

	return result, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserUsecase.GetUsers(ctx)
	if err != nil {
		return nil, err
	}

	var result []*model.User
	for _, u := range users {
		result = append(result, &model.User{
			ID:       u.ID,
			FullName: u.FullName,
			Email:    u.Email,
		})
	}

	return result, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
