// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Post struct {
	ID string `json:"id"`
	Title string `json:"title"`
	Description string `json:"description"`
	User *User `json:"user"`
}

type User struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Email string `json:"email"`
}