FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN go install github.com/air-verse/air@v1.61.7

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", "deployment/docker/.air.toml"]
