// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPost struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type NewUser struct {
	FullName string `json:"fullName"`
	Email    string `json:"email"`
}

type Post struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"id"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
}

type VerifyOTPInput struct {
	Email string `json:"email"`
	Otp   string `json:"otp"`
}
